# Default values for squadron.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

mongodb:
  usePassword: false
  service:
    port: 27017
  persistence:
    storageClass: local-storage
    size: 5Gi
    existingClaim: mongo-local-pv-claim
