apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-deployment
  labels:
    app: session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
    spec:
      containers:
      - name: session
        image: session
        imagePullPolicy: Never
        ports:
            - containerPort: 9094