sudo: required
dist: trusty

services:
- docker

install:
- docker-compose -f ./user_management/docker-compose.yml  pull
- docker-compose -f ./user_management/docker-compose.yml build
- docker-compose -f ./PostProcessing/docker-compose.yml  pull
- docker-compose -f ./PostProcessing/docker-compose.yml  build
- docker-compose -f ./ModelService/docker-compose.yml pull
- docker-compose -f ./ModelService/docker-compose.yml build

script:
- docker-compose -f ./user_management/docker-compose.yml run --no-deps --rm app user_management/manage.py test api -v 2;
- docker-compose -f ./ModelService/docker-compose.yml run app python modeltest.py
- docker-compose -f ./PostProcessing/docker-compose.yml run app python testPP.py 
