sudo: required
dist: trusty

services:
- docker

install:
- docker-compose -f ./user_management/docker-compose.yml  pull
- docker-compose -f ./user_management/docker-compose.yml build
- docker build -t session ./session.management
- docker build -t data_retrieval ./DataRetrieval

script:
- docker run session /bin/bash -c "mvn test"
- docker run data_retrieval /bin/bash -c "cd handlers; go test"
- docker-compose -f ./user_management/docker-compose.yml run --no-deps --rm app user_management/manage.py test api -v 2;
