---
version: '2'
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:3.0.1
    ports: 
      - "8081:8081"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 8081
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:8088:8088


  kafka1:
    image: confluentinc/cp-kafka:3.0.1
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper1

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 0.0.0.0:8081
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:8082