apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-deployment
  labels:
    app: data
  annotations:
      timestamp: {{ .Values.timestamp }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: squadronteam/data
        imagePullPolicy: Always
        ports:
            - containerPort: 9093
        env:
        - name: KAFKA
          value: kafka1:9092
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "9093"