apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
  labels:
    app: model
spec:
  replicas: {{ .Values.replicaCount}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
      annotations:
        timestamp: {{ .Values.timestamp }}
    spec:
      containers:
      - name: model
        image: squadronteam/model
        imagePullPolicy: Always
        ports:
            - containerPort: 9094
        env:
        - name: KAFKA
          value: kafka1:9092