apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post
spec:
  replicas: {{ .Values.replicaCount}}
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
      annotations:
        timestamp: {{ .Values.timestamp }}
    spec:
      containers:
      - name: post
        image: squadronteam/post
        imagePullPolicy: Always
        ports:
            - containerPort: 9095
        env:
        - name: KAFKA
          value: kafka1:9092