apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: {{ .Values.replicaCount}}
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
      annotations:
        timestamp: {{ .Values.timestamp }}
    spec:
      containers:
      - name: ui
        image: squadronteam/ui
        imagePullPolicy: Always
        ports:
            - containerPort: 8080
              name: ui-port
        env:
        - name: FLOATING_IP
          value: {{ .Values.master_ip }}