apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
      annotations:
        timestamp: {{ .Values.timestamp }}
    spec:
      containers:
      - name: user
        image: squadronteam/user
        imagePullPolicy: Always
        ports:
            - containerPort: 8000