apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:3.0.1
        ports:
        - containerPort: 2181
        env:
          - name: ZOOKEEPER_SERVER_ID
            value: "1"
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value : "2000"
          - name: ZOOKEEPER_INIT_LIMIT
            value: "5"
          - name: ZOOKEEPER_SYNC_LIMIT
            value: "2"