kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-local-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi