on:
  push:
    branches:
      - github_test
jobs:
  sshtest:
    name: Build
    runs-on: ubuntu-latest
   step:  
      name: Generating_key
      run: cat SECRET > jetstream_key
      env: 
        SECRET: ${{ secrets.jetstream_key }}
      
      name: ssh to the jestream server
      run: ssh -i jetstream_key ubuntu@149.165.170.106
      
      name: create directory
      run: mkdir testssh
	
