on:
  push:
    branches:
      - github_test
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: ToDo
        run: echo "need to setup tests"
  
  deploy:
    name: Trigger deployement
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: generating keys
        run: echo "$DEPLOY_KEY" > github_deploy && chmod 0400 github_deploy
        env:
          DEPLOY_KEY: ${{ secrets.deploy_key }}
      - name: Initialize repo
        run: GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -i github_deploy' git clone git@github.com:airavata-courses/Squadron.git
      - name: check if there is change in version to deploy
        run: if git diff --name-only HEAD~1 | grep -q "^version$"; then export TRIGGER_DEPLOY=0; else export TRIGGER_DEPLOY=$?; fi; echo "TRIGGER_DEPLOY is set to $TRIGGER_DEPLOY"
        working-directory: Squadron
      - name: tag commit for deployment
        if: env.TRIGGER_DEPLOY == 0
        run: echo "TRIGGER_DEPLOY is set to $TRIGGER_DEPLOY" && git tag v$(cat version)" && git push origin v$(cat version)
        working-directory: Squadron
