on:
  push:
    branches:
      - github_test
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: ToDo
        run: echo "need to setup tests"
  
  deploy:
    name: Trigger deployement
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: generating keys
        run: echo "$DEPLOY_KEY" > github_deploy
        env:
          DEPLOY_KEY: ${{ secrets.deploy_key }}
      - name: Initialize repo
        run: GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -i github_deploy' git clone git@github.com:airavata-courses/Squadron.git && cd Squadron
      - name: check if there is change in version to deploy
        run: git diff --name-only HEAD~1 | grep "^version$"  || export $TRIGGER_DEPLOY=$?
      - name: tag commit for deployment
        if: env.TRIGGER_DEPLOY == 0
        run: git tag -a v$(cat version) -m "automatically tagged version $(cat version) via github actions" && git push origin v$(cat version)
