on:
  push:
    branches:
      - github_test
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: ToDo
        run: echo "need to setup tests"
  
  deploy:
    name: Trigger deployement
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: generating keys
        run: echo "$DEPLOY_KEY" > github_deploy && chmod 0400 github_deploy
        env:
          DEPLOY_KEY: ${{ secrets.deploy_key }}
      - name: Initialize repo
        run: GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -i github_deploy' git clone git@github.com:airavata-courses/Squadron.git
      - name: mark commit for deployement if version changed
        run: |
          if git diff --name-only HEAD~1 | grep -q "^version$"
          then
            echo "Marking commit for deployment"
            git tag v$(cat version) && git push origin v$(cat version)
          else 
            echo "check returned status: $?, assuming that this means there is nothing to deploy"
          fi
        working-directory: Squadron
