on:
  push:
    branches:
      - github_test
jobs:
  sshtest:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Generating_key
      run: echo "$SECRET" > jetstream_key && chmod 0600 jetstream_key
      env: 
        SECRET: ${{ secrets.jetstream_key }}
        
    - name: create file on jestream server
      run: ssh -i jetstream_key ubuntu@149.165.170.106 "date > test_file"
