on:
  push:
    branches:
      - github_test
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: ToDo
        run: echo "need to setup tests"
  
  deploy:
    name: Trigger deployement
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run tests
        uses: ./.github/actions/run_tests
